# [Continuous integration (CI) workflow](https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions)

name: PII Removal

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      
    - name: Install lib requirements
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpoppler-cpp-dev pkg-config python3-dev
        
    - name: Create output for pytest 
      run: mkdir -p $PIIHOME/output     
      
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Lint with flake8
      run: |
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
        
    - name: Run pytest to verify PII are deleted
      run: |
        pytest -s -v
